import Link from '@/ui/link';
import { session } from '@/modules/auth/session';
import { PageHeading, Empty, date } from '@/ui/common';
import { Icon } from '@/ui/icon';
import { profileCompletion } from '@/modules/candidates/profile';
export default async function CandidateHome() {
  const {client,user}=await session();
  const {data:profile}=await client.from('candidates').select('*').eq('user_id',user.id).maybeSingle();
  const [entries,apps,notifications]=await Promise.all([client.from('profile_entries').select('kind,title,organization').eq('candidate_id',profile?.id || '00000000-0000-0000-0000-000000000000'),client.from('applications').select('id',{count:'exact',head:true}).eq('status','active'),client.from('notifications').select('*').order('created_at',{ascending:false}).limit(5)]);
  const progress=profileCompletion(profile,entries.data||[]);
  return <><PageHeading eyebrow="SUA TRAJETÓRIA" title={`Olá, ${profile?.full_name.split(' ')[0] || 'boas-vindas'}!`} description="Vamos encontrar seu próximo passo juntos."><Link href="/vagas" className="button primary">Explorar vagas <Icon name="arrow_forward"/></Link></PageHeading><div className="split"><div><div className="card"><div className="card-header"><h2>Seu perfil, sua história</h2><strong>{progress}%</strong></div><div className="progress-track" role="progressbar" aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100} aria-label="Completude do perfil"><span style={{width:`${progress}%`}}/></div><p className="muted" style={{marginTop:18}}>Mantenha suas experiências e seu currículo atualizados para apresentar sua trajetória.</p><Link className="button tonal" href="/candidato/perfil">{profile?'Atualizar meu currículo':'Começar meu perfil'}</Link>{profile && <p className="muted" style={{fontSize:11,marginTop:15,marginBottom:0}}>Última atualização: {date(profile.updated_at,true)}</p>}</div><div className="card"><h2>Últimas atualizações</h2>{notifications.data?.length?<ul className="timeline">{notifications.data.map(n=><li key={n.id}><strong>{n.title}</strong><p>{n.body}</p><small>{date(n.created_at,true)}</small></li>)}</ul>:<Empty title="Tudo em dia por aqui" description="As atualizações das suas candidaturas aparecerão neste espaço." icon="notifications_none"/>}</div></div><div><div className="metric"><div className="metric-top">Candidaturas em andamento<Icon name="work_outline"/></div><strong>{apps.count||0}</strong><Link className="text-link" href="/candidato/candidaturas">Acompanhar candidaturas</Link></div><div className="card" style={{marginTop:20}}><Icon name="shield"/><h3 style={{marginTop:14}}>Você no controle</h3><p className="muted">Revise seus dados e gerencie sua participação no banco de talentos.</p><Link className="text-link" href="/candidato/privacidade">Minha privacidade <Icon name="arrow_forward"/></Link></div></div></div></>;
}
