begin;
create extension if not exists pgtap with schema extensions;
set search_path to public,extensions;
select plan(18);
select ok(not has_function_privilege('anon','public.claim_email_delivery(text)','EXECUTE'),'Anônimo não reserva entrega');
select ok(not has_function_privilege('authenticated','public.claim_email_delivery(text)','EXECUTE'),'Usuário não reserva entrega');
select ok(not has_function_privilege('authenticated','public.finish_email_delivery(text,uuid,boolean)','EXECUTE'),'Usuário não altera recibos');
select ok(not has_table_privilege('authenticated','private.email_hook_deliveries','SELECT'),'Recibos não expostos ao usuário');
select ok(not has_table_privilege('service_role','private.email_hook_deliveries','INSERT'),'Serviço só escreve por RPC');
select ok((select relrowsecurity from pg_class where oid='private.email_hook_deliveries'::regclass),'RLS ativo');
create temporary table lease_test(value jsonb);
grant all on lease_test to service_role;
set local role service_role;
insert into lease_test values(public.claim_email_delivery(repeat('a',64)));
select is((select value->>'state' from lease_test),'claimed','Serviço reserva entrega');
select is(public.claim_email_delivery(repeat('a',64))->>'state','busy','Segunda reserva bloqueada');
select ok(not public.finish_email_delivery(repeat('a',64),'00000000-0000-4000-8000-000000000000',true),'Lease errado não conclui');
select ok(public.finish_email_delivery(repeat('a',64),(select (value->>'lease')::uuid from lease_test),true),'Lease correto conclui');
select is(public.claim_email_delivery(repeat('a',64))->>'state','sent','Retry entregue não reserva de novo');
select throws_ok($$select public.claim_email_delivery('invalid')$$,'P0001','invalid_delivery_key','Chave inválida recusada');
delete from lease_test;
insert into lease_test values(public.claim_email_delivery(repeat('b',64)));
select ok(public.finish_email_delivery(repeat('b',64),(select (value->>'lease')::uuid from lease_test),false),'Falha libera reserva');
select is(public.claim_email_delivery(repeat('b',64))->>'state','claimed','Nova tentativa possível após falha');
reset role;
update private.email_hook_deliveries set lease_until=now()-interval '1 second' where key=repeat('b',64);
set local role service_role;
delete from lease_test;
insert into lease_test values(public.claim_email_delivery(repeat('b',64)));
select is((select value->>'state' from lease_test),'claimed','Lease expirado pode ser retomado');
select is(public.claim_email_delivery(repeat('b',64))->>'state','busy','Lease retomado bloqueia disputa');
reset role;
update private.email_hook_deliveries set created_at=now()-interval '3 days' where key=repeat('a',64);
set local role service_role;
select is(public.claim_email_delivery(repeat('a',64))->>'state','claimed','Recibo antigo é limpo');
reset role;
select ok(not exists(select 1 from information_schema.columns where table_schema='private'
 and table_name='email_hook_deliveries' and column_name in ('email','recipient','body','token','code')),'Recibos sem campos de dados pessoais');
select * from finish();
rollback;
