-- Somente para `supabase db reset --local`. Nunca executar em cloud.
update private.security_config set allow_local_password_staff=true where singleton;
insert into public.departments(name) values ('Tecnologia'),('Qualidade'),('Produção'),('Pessoas e Cultura'),('Comercial'),('Logística');
insert into public.interest_areas(name) values ('Tecnologia'),('Pesquisa e Desenvolvimento'),('Qualidade'),('Produção'),('Administrativo'),('Comercial'),('Logística');
insert into public.tags(name) values ('Primeiro emprego'),('Experiência em indústria'),('Disponibilidade imediata');
insert into public.talent_pools(name,description) values ('Talentos em desenvolvimento','Perfis fictícios para treinamento local.');
insert into public.privacy_policies(version,title,body,published_at,active) values
('LOCAL-TESTE-1','Aviso para ambiente local de testes','Este aviso é exclusivamente para testes com dados fictícios. A Herbamed precisa aprovar o aviso real, a finalidade, a base legal, os prazos de retenção e os canais de contato antes de utilizar dados pessoais reais. O portal registra candidaturas, informações profissionais, documentos e o histórico do processo seletivo. Solicitações de acesso, correção e exclusão podem ser feitas pela central de privacidade. O consentimento para o banco de talentos é uma escolha independente da candidatura.',now(),true);
insert into public.jobs(slug,title,department_id,city,state,work_model,contract_type,description,responsibilities,requirements,benefits,status,published_at,openings) values
('analista-de-qualidade-local-001','Analista de Qualidade',(select id from public.departments where name='Qualidade'),'Joinville','SC','Presencial','CLT','Atue na construção de processos de qualidade para produtos nutracêuticos, em parceria com as áreas de produção e desenvolvimento. Esta vaga é fictícia para testes locais.','Acompanhar indicadores, apoiar investigações de desvios e documentar melhorias.','Experiência com gestão da qualidade e atenção a boas práticas de fabricação.','Desenvolvimento profissional e ambiente colaborativo.','published',now(),1),
('desenvolvedor-full-stack-local-002','Desenvolvedor(a) Full Stack',(select id from public.departments where name='Tecnologia'),'Joinville','SC','Híbrido','CLT','Ajude a construir ferramentas digitais que apoiam a operação e a experiência das pessoas na Herbamed. Esta vaga é fictícia para testes locais.','Criar interfaces acessíveis, APIs seguras e evoluir a plataforma junto com a equipe.','Experiência com TypeScript, React, PostgreSQL e testes automatizados.','Autonomia para propor soluções e aprendizado contínuo.','published',now(),1),
('assistente-de-logistica-local-003','Assistente de Logística',(select id from public.departments where name='Logística'),'Joinville','SC','Presencial','CLT','Apoie o fluxo de materiais e entregas com organização e cuidado. Esta vaga é fictícia para testes locais.','Acompanhar pedidos, organizar registros e apoiar o controle operacional.','Organização, comunicação e conhecimento de ferramentas de escritório.','Integração com diferentes áreas e oportunidade de crescimento.','published',now(),2);
insert into public.job_stages(job_id,name,position,terminal)
select j.id,s.name,s.position,s.terminal from public.jobs j cross join (values ('Inscrição',0,false),('Triagem',1,false),('Entrevista RH',2,false),('Entrevista com gestor',3,false),('Proposta',4,false),('Contratado',5,true),('Não selecionado',6,true)) as s(name,position,terminal);
insert into public.job_questions(job_id,label,required,position) select id,'Conte brevemente por que esta oportunidade combina com sua trajetória.',true,0 from public.jobs where slug='desenvolvedor-full-stack-local-002';
