import { requirePermission } from '@/modules/auth/session';
import { PageHeading } from '@/ui/common';
import { ActionForm, Field, Hidden } from '@/ui/form';
import { mutate } from '@/modules/actions';
export default async function Settings() {
  const {client}=await requirePermission('settings.manage');
  const [{data:settings},{data:departments},{data:areas},{data:tags},{data:pools}]=await Promise.all([client.from('settings').select('*'),client.from('departments').select('*').order('name'),client.from('interest_areas').select('*').order('name'),client.from('tags').select('*').order('name'),client.from('talent_pools').select('*').order('name')]);
  const get=(key:string)=>settings?.find(s=>s.key===key)?.value;
  const catalogs=[['departments','Departamentos',departments],['interest_areas','Áreas de interesse',areas],['tags','Tags',tags],['talent_pools','Pools de talentos',pools]] as const;
  return <><PageHeading eyebrow="ADMINISTRAÇÃO" title="Configurações" description="Parâmetros e cadastros de apoio da plataforma."/><div className="split"><div>{catalogs.map(([key,label,items])=><div className="card" key={key}><h2>{label}</h2>{items?.map(item=><div className="file-row" key={item.id}><strong>{item.name}</strong><span>{item.active?'Ativo':'Inativo'}</span></div>)}<ActionForm action={mutate} submit="Adicionar" className="inline-form"><Hidden name="op" value="catalog"/><Hidden name="catalog" value={key}/><Hidden name="active" value="true"/><Field name="name" label={`Novo ${label.toLowerCase()}`} required/></ActionForm></div>)}</div><aside className="card"><h2>Preferências</h2><ActionForm action={mutate} submit="Salvar nome"><Hidden name="op" value="setting"/><Hidden name="key" value="app_name"/><Field name="value" label="Nome da aplicação" value={typeof get('app_name')==='string'?String(get('app_name')):'Herbamed Carreiras'} required/></ActionForm><hr style={{border:0,borderTop:'1px solid var(--border)',margin:'24px 0'}}/><ActionForm action={mutate} submit="Salvar limite"><Hidden name="op" value="setting"/><Hidden name="key" value="max_interest_areas"/><Field name="value" label="Máximo de áreas de interesse" type="number" value={typeof get('max_interest_areas')==='number'?Number(get('max_interest_areas')):3} min={1} max={10} required/></ActionForm><p className="muted" style={{fontSize:11,marginTop:20}}>O nome público também usa APP_NAME até sincronização de cache e metadados na próxima publicação.</p></aside></div></>;
}
