import Link from '@/ui/link';
import Image from 'next/image';
import { PublicShell } from '@/ui/public-shell';
import { Icon } from '@/ui/icon';
import { JobsList } from '@/modules/jobs/list';
export default async function Home() {
  return <PublicShell><section className="hero container"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> SUA PRÓXIMA HISTÓRIA COMEÇA AQUI</p><h1>Seu talento.<br />Nosso propósito.<br /><em>Um futuro em comum.</em></h1><p className="hero-description">Há espaço para a sua trajetória na Herbamed. Conheça nossas oportunidades e encontre o próximo passo da sua carreira.</p><div className="actions"><Link href="/vagas" className="button primary">Encontre sua oportunidade <Icon name="arrow_forward" /></Link><Link href="/banco-de-talentos" className="button text">Cadastre seu currículo</Link></div><div className="hero-footnote"><Icon name="verified_user" /> Um processo simples, transparente e com respeito aos seus dados.</div></div><div className="hero-art" aria-hidden="true"><div className="art-circle"><Image src="/brand/folha.png" alt="" width={181} height={183} /></div><div className="art-caption"><span>GENTE QUE CRESCE JUNTO</span><strong>O próximo capítulo<br />pode ser seu.</strong><div className="art-line" /></div></div></section>
    <section className="opportunities container" id="oportunidades"><div className="section-heading"><div><p className="eyebrow">CONSTRUA SUA TRAJETÓRIA</p><h2>Encontre o seu lugar</h2><p className="muted">Explore as oportunidades abertas na Herbamed.</p></div><Link href="/vagas" className="text-link">Ver todas as vagas <Icon name="arrow_forward" /></Link></div><JobsList limit={3} /></section>
    <section className="process-section container"><div><p className="eyebrow">CADA PASSO, COM CLAREZA</p><h2>Mais perto da sua<br />próxima oportunidade.</h2><p className="muted">Você acompanha sua candidatura em um só lugar.</p></div><ol className="process-steps">{[['01','Conte sua história','Crie seu perfil, adicione suas experiências e envie seu currículo.'],['02','Encontre uma oportunidade','Escolha a vaga que faz sentido para o seu momento profissional.'],['03','Acompanhe cada etapa','Consulte atualizações e converse com a nossa equipe pelo portal.']].map(([n,t,d])=><li key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></li>)}</ol></section>
    <section className="talent-banner container"><div><p className="eyebrow">AS POSSIBILIDADES CONTINUAM</p><h2>Não encontrou sua vaga?</h2><p>Faça parte do nosso banco de talentos e mantenha seu perfil atualizado.</p></div><Link href="/banco-de-talentos" className="button primary">Quero fazer parte <Icon name="arrow_forward" /></Link></section>
    <section className="faq container"><h2>Podemos ajudar?</h2><details><summary>Posso cadastrar meu currículo sem uma vaga aberta?</summary><p>Sim. No banco de talentos você pode completar seu perfil e escolher suas áreas de interesse.</p></details><details><summary>Como acompanho minha candidatura?</summary><p>Entre em Minha área para consultar a etapa atual, entrevistas e mensagens da equipe.</p></details><details><summary>Como posso atualizar ou excluir meus dados?</summary><p>Seu perfil pode ser editado a qualquer momento. Na central de privacidade, você pode solicitar acesso, correção ou exclusão.</p></details></section>
  </PublicShell>;
}
