import Form from 'next/form';
import { SubmitButton } from '@/ui/submit-button';
import Link from '@/ui/link';
import { requirePermission } from '@/modules/auth/session';
import { PageHeading, Badge, Empty, date, statusLabels } from '@/ui/common';
export default async function AdminJobs({searchParams}:{searchParams:Promise<{q?:string;status?:string;page?:string}>}) {
  const {client}=await requirePermission('jobs.read');const p=await searchParams;const page=Math.max(1,Math.min(1000,Number(p.page)||1));
  let query=client.from('jobs').select('*',{count:'exact'}).order('created_at',{ascending:false}).range((page-1)*20,page*20-1);
  if(p.q)query=query.ilike('title',`%${p.q.replace(/[%_]/g,'').slice(0,100)}%`);
  if(p.status)query=query.eq('status',p.status);
  const {data,count,error}=await query;
  return <><PageHeading eyebrow="RECRUTAMENTO" title="Vagas" description="Organize, publique e acompanhe suas oportunidades."><Link className="button primary" href="/rh/vagas/nova">Nova vaga +</Link></PageHeading><Form className="search-bar" action="/rh/vagas"><label className="field"><span>Buscar vaga</span><input name="q" defaultValue={p.q} placeholder="Título"/></label><label className="field"><span>Status</span><select name="status" defaultValue={p.status}><option value="">Todos</option>{['draft','pending','published','paused','closed','cancelled','archived'].map(s=><option key={s} value={s}>{statusLabels[s]}</option>)}</select></label><SubmitButton className="button primary" pendingLabel="Buscando…">Filtrar</SubmitButton></Form><div className="card">{error?<p role="alert">Não foi possível carregar as vagas.</p>:data?.length?<div className="table-wrap"><table><thead><tr><th>Vaga</th><th>Local</th><th>Modelo</th><th>Status</th><th>Criada em</th><th></th></tr></thead><tbody>{data.map(j=><tr key={j.id}><td><strong>{j.title}</strong><small>Código {j.code}</small></td><td>{j.city}</td><td>{j.work_model}</td><td><Badge tone={j.status}>{statusLabels[j.status]}</Badge></td><td>{date(j.created_at)}</td><td><Link className="text-link" href={`/rh/vagas/${j.id}`}>Gerenciar</Link></td></tr>)}</tbody></table></div>:<Empty title="Nenhuma vaga encontrada" description="Crie uma oportunidade ou ajuste os filtros." href="/rh/vagas/nova" action="Criar vaga" icon="work_outline"/>}</div><div className="pagination">{page>1&&<Link href={`?q=${encodeURIComponent(p.q||'')}&status=${p.status||''}&page=${page-1}`}>Anterior</Link>}<span>{count||0} vagas · Página {page}</span>{page*20<(count||0)&&<Link href={`?q=${encodeURIComponent(p.q||'')}&status=${p.status||''}&page=${page+1}`}>Próxima</Link>}</div></>;
}
