import { requirePermission } from '@/modules/auth/session';
import { PageHeading, Empty, Badge } from '@/ui/common';
import { ActionForm, Field, Hidden, Select } from '@/ui/form';
import { mutate } from '@/modules/actions';
export default async function Users() {
  const {client}=await requirePermission('users.manage');
  const [{data:staff},{data:roles},{data:assignments}]=await Promise.all([client.from('staff').select('*').order('created_at',{ascending:false}),client.from('roles').select('id,name').eq('active',true).order('name'),client.from('staff_roles').select('user_id,role_id')]);
  return <><PageHeading eyebrow="ADMINISTRAÇÃO" title="Usuários internos" description="Atribua acesso somente após a pessoa entrar com Microsoft e confirmar a conta."/><div className="split"><div className="card"><h2>Equipe com acesso</h2>{staff?.length?<div className="table-wrap"><table><thead><tr><th>Nome</th><th>Perfil</th><th>Status</th></tr></thead><tbody>{staff.map(s=><tr key={s.user_id}><td><strong>{s.display_name}</strong><small>{s.user_id}</small></td><td>{roles?.find(r=>r.id===assignments?.find(a=>a.user_id===s.user_id)?.role_id)?.name||'—'}</td><td><Badge tone={s.active?'green':'pending'}>{s.active?'Ativo':'Inativo'}</Badge></td></tr>)}</tbody></table></div>:<Empty title="Equipe não cadastrada" description="Adicione usuários autorizados após o primeiro acesso Microsoft." icon="admin_panel_settings"/>}</div><div className="card"><h2>Conceder ou atualizar acesso</h2><ActionForm action={mutate} submit="Salvar acesso"><Hidden name="op" value="staff"/><Field name="email" label="E-mail Microsoft" type="email" required/><Field name="name" label="Nome exibido" required/><Select name="role_id" label="Perfil de acesso" required><option value="">Selecione</option>{roles?.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</Select><label className="check"><input type="checkbox" name="active" defaultChecked/>Acesso ativo</label></ActionForm></div></div></>;
}
