import Link from 'next/link';
import { requirePermission } from '@/modules/auth/session';
import { PageHeading, Empty, Badge, date } from '@/ui/common';
import { Icon } from '@/ui/icon';
export default async function Dashboard() {
  const {client}=await requirePermission('dashboard.read');
  const [jobs,applications,candidates,interviews,recent]=await Promise.all([client.from('jobs').select('id',{count:'exact',head:true}).eq('status','published'),client.from('applications').select('id',{count:'exact',head:true}).eq('status','active'),client.from('candidates').select('id',{count:'exact',head:true}).is('archived_at',null),client.from('interviews').select('id',{count:'exact',head:true}).eq('status','scheduled').gte('starts_at',new Date().toISOString()),client.from('applications').select('id,job_id,candidate_id,created_at').order('created_at',{ascending:false}).limit(6)]);
  const cids=recent.data?.map(a=>a.candidate_id)||[],jids=recent.data?.map(a=>a.job_id)||[];
  const [people,positions]=await Promise.all([cids.length?client.from('candidates').select('id,full_name').in('id',cids):Promise.resolve({data:[]}),jids.length?client.from('jobs').select('id,title').in('id',jids):Promise.resolve({data:[]})]);
  return <><PageHeading eyebrow="BOM DIA, EQUIPE HERBAMED" title="Visão geral" description="Um retrato do recrutamento agora."><Link className="button primary" href="/rh/vagas/nova">Criar nova vaga <Icon name="add"/></Link></PageHeading><div className="metrics">{[['Vagas publicadas',jobs.count||0,'work_outline','/rh/vagas'],['Candidaturas ativas',applications.count||0,'assignment','/rh/candidaturas'],['Candidatos',candidates.count||0,'group','/rh/candidatos'],['Entrevistas agendadas',interviews.count||0,'event','/rh/entrevistas']].map(([label,count,icon,href])=><Link href={String(href)} className="metric" key={String(label)}><div className="metric-top"><span>{label}</span><Icon name={String(icon)}/></div><strong>{count}</strong><small>Ver detalhes →</small></Link>)}</div><div className="dashboard-grid"><div className="card"><div className="card-header"><h2>Candidaturas recentes</h2><Link className="text-link" href="/rh/candidaturas">Ver todas</Link></div>{recent.data?.length?<div className="table-wrap"><table><thead><tr><th>Candidato</th><th>Vaga</th><th>Data</th><th></th></tr></thead><tbody>{recent.data.map(a=><tr key={a.id}><td><strong>{people.data?.find(c=>c.id===a.candidate_id)?.full_name||'Candidato'}</strong></td><td>{positions.data?.find(j=>j.id===a.job_id)?.title||'—'}</td><td>{date(a.created_at)}</td><td><Link className="text-link" href={`/rh/candidaturas/${a.id}`}>Abrir</Link></td></tr>)}</tbody></table></div>:<Empty title="Sem candidaturas recentes" description="Assim que alguém se candidatar, o histórico aparecerá aqui." icon="assignment"/>}</div><div className="card"><div className="card-header"><h2>Próximas ações</h2><Badge>RH</Badge></div><p className="muted">Mantenha as vagas e os candidatos em movimento.</p><div className="nav-group"><Link className="nav-link" href="/rh/vagas"><Icon name="work_outline"/>Gerenciar vagas</Link><Link className="nav-link" href="/rh/talentos"><Icon name="person_search"/>Buscar talentos</Link><Link className="nav-link" href="/rh/entrevistas"><Icon name="event"/>Conferir agenda</Link></div></div></div></>;
}
