import Link from 'next/link';
import { session } from '@/modules/auth/session';
import { PageHeading, Empty, date, Badge } from '@/ui/common';
import { ActionForm, Hidden, Select, TextArea } from '@/ui/form';
import { mutate } from '@/modules/actions';
export default async function MyPrivacy() {
  const {client,user}=await session();
  const {data:profile}=await client.from('candidates').select('id,talent_pool').eq('user_id',user.id).maybeSingle();
  const [{data:policy},{data:requests}]=await Promise.all([client.from('privacy_policies').select('id,version,title').eq('active',true).maybeSingle(),profile?client.from('privacy_requests').select('*').eq('candidate_id',profile.id).order('created_at',{ascending:false}):Promise.resolve({data:[]})]);
  return <><PageHeading eyebrow="SEUS DADOS" title="Central de privacidade" description="Transparência e controle sobre seus dados pessoais."/><div className="split"><div><div className="card"><h2>Banco de talentos</h2><p>Escolha se o RH pode considerar seu perfil para oportunidades futuras, além das vagas em que você se candidatou.</p>{profile&&policy?<ActionForm action={mutate} submit="Salvar minha preferência"><Hidden name="op" value="privacy-consent"/><Hidden name="policy_id" value={policy.id}/><label className="check"><input name="talent_pool" type="checkbox" defaultChecked={profile.talent_pool}/>Quero participar do banco de talentos</label><p className="muted">Aviso vigente: {policy.title} (versão {policy.version}). <Link className="text-link" href="/privacidade">Ler aviso</Link></p></ActionForm>:<p>Complete seu perfil para salvar esta escolha.</p>}</div><div className="card"><h2>Minhas solicitações</h2>{requests?.length?requests.map(r=><div className="file-row" key={r.id}><div><strong>{r.kind}</strong><br/><small>Protocolo {r.id} · {date(r.created_at)}</small></div><Badge>{r.status}</Badge></div>):<Empty title="Sem solicitações" description="Quando fizer uma solicitação, acompanhe aqui a análise e a resposta." icon="shield"/>}</div></div><div><div className="card"><h2>Solicitar análise</h2>{profile?<ActionForm action={mutate} submit="Enviar solicitação"><Hidden name="op" value="privacy-request"/><Select name="kind" label="Tipo de solicitação" required><option value="access">Acesso aos dados</option><option value="correction">Correção</option><option value="deletion">Exclusão</option><option value="portability">Portabilidade</option><option value="revocation">Revogar participação</option><option value="information">Informações sobre tratamento</option></Select><TextArea name="detail" label="Detalhes (opcional)"/></ActionForm>:<p>Complete seu perfil para abrir uma solicitação.</p>}</div><div className="card"><h2>Exportar meus dados</h2><p className="muted">Baixe uma cópia dos dados estruturados armazenados neste portal.</p><a className="button outlined" href="/api/my-data">Baixar JSON</a></div></div></div></>;
}
